### ISSUE TITLE
Failed to download payload (code: FFFFFFFF)

### ISSUE THREAD

**Issue by sh1ku** [Dazzozo/humblehax#1]
New 3DS XL on 11.0.0-33E. 
I guess it's because there is no payload download for ver. 11? Works flawlessly if you set the version to download to 10.7.0-32E, they payload is installed, and HBL loads after launching the game.

As I'm not sure what exactly the issue is, I'm putting it here.

Kind regards,

Alberto Salazar

**Comment by dazjo** [comment]
https://github.com/shinyquagsire23/supermysterychunkhax/issues/6
